name: 在线编译EnsWilde

on:
  workflow_dispatch: # 开启手动点击触发功能

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 检出源码 (Checkout)
        uses: actions/checkout@v4

      - name: 设定 Xcode 编译环境
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: 编译无签名版本 (Build Unsigned)
        run: |
          xcodebuild clean build \
            -project EnsWilde.xcodeproj \
            -scheme EnsWilde \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CONFIGURATION_BUILD_DIR="$(pwd)/build"

      - name: 封包为 IPA 文件 (Package to IPA)
        run: |
          mkdir -p Payload
          mv build/EnsWilde.app Payload/
          zip -r EnsWilde-Loon.ipa Payload

      - name: 导出安装包 (Upload Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: EnsWilde-Loon-Version
          path: EnsWilde-Loon.ipa
